config/routes.rb
Rails.application.routes.draw do
  get 'tmlmqist', to: 'pages#tmlmqist',as: 'tmlmqist'
  get 'question', to: 'pages#question', as: 'question'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def tmlmqist
        respond_to do |format|
          format.html { render :tmlmqist }
        end
    end
    
    
    
    
    
    
    def question
      q="Which of the following is the Single Responsiblity Principle?"


      answers=[ "a) A class should have only one reason to change.",
      "b) Each developer on a team should have one main responsiblity.",
      "c) Every app will have one responsiblity that is most important to users."
      ]

      respond_to do |format|
        format.html {render :question, locals:{q:q,answers:answers}}
      end
    end
end    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeworkProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/question.html.erb



<h1>Practice Question</h1>
<p>
<%= q %>
</p>
<ul>
<% answers.each do |a| %>
<li><%= a %></li>
<% end %>
</ul>


<p><%= link_to 'Profile Page', tmlmqist_path %> </p>

app/views/pages/tmlmqist.html.erb
<h1>Travis Malmquist's page</h1>

<p>
Welcome to Travis' page. Here lies stuff.</p>

<h2>Here we have:</h2>

<ul>
<li>Words</li>
<li>A picture</li>
<li>Other stuff</li>
<li><%= link_to "My other Page", "https://quizlet.com", target: "_blank" %></li>
</ul>


 <%= image_tag "2015-09-02 07.44.25.jpg", height: 300 %>
